# Generated by Django 2.2 on 2019-06-02 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('A', 'admin'), ('U', 'user')], max_length=1)),
                ('occupation', models.CharField(choices=[('dev', 'developer'), ('des', 'designer')], max_length=3)),
                ('year', models.CharField(choices=[('1', 'first_year'), ('2', 'second_year'), ('3', 'third_year'), ('4', 'fourth_year'), ('5', 'fifth_year')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
