# Generated by Django 2.2 on 2019-06-02 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imgsched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('name_of_meeting', models.CharField(max_length=254)),
                ('description_of_meeting', models.TextField()),
                ('meeting_on', models.DateTimeField()),
                ('venue', models.CharField(default='IMG Lab', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='imgsched.UserProfile')),
                ('member', models.ManyToManyField(related_name='invite_peoples', to='imgsched.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgsched.Meeting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgsched.UserProfile')),
            ],
        ),
    ]
