# Generated by Django 2.2 on 2019-06-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgsched', '0002_comment_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='imgsched.Meeting'),
        ),
    ]
